import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CartProvider from "@/context/cartContext";
import CartDrawer from "@/components/CartDrawer";



const inter = Inter({
 subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable}  h-full antialiased`}
    >
    <body className= {`${inter.className} min-h-full flex flex-col`}>
     <CartProvider>
 <Navbar></Navbar>
<CartDrawer></CartDrawer>
        <main className="">
 {children}
        </main>
        <Footer></Footer>
        
     </CartProvider>
      
        </body>
    </html>
  );
}
